/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_learner_core_CertificateTemplate */

#ifndef _Included_org_learner_core_CertificateTemplate
#define _Included_org_learner_core_CertificateTemplate
#ifdef __cplusplus
extern "C" {
#endif
#undef org_learner_core_CertificateTemplate_ID_TYPE_NONE
#define org_learner_core_CertificateTemplate_ID_TYPE_NONE 0L
#undef org_learner_core_CertificateTemplate_ID_TYPE_DNS
#define org_learner_core_CertificateTemplate_ID_TYPE_DNS 1L
#undef org_learner_core_CertificateTemplate_ID_TYPE_IPADDR
#define org_learner_core_CertificateTemplate_ID_TYPE_IPADDR 2L
#undef org_learner_core_CertificateTemplate_ID_TYPE_EMAIL
#define org_learner_core_CertificateTemplate_ID_TYPE_EMAIL 3L
/*
 * Class:     org_learner_core_CertificateTemplate
 * Method:    initcert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_learner_core_CertificateTemplate_initcert
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
